name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # Ganti dengan nama akun Docker Hub Anda (misalnya: myuser/my-app)
  DOCKER_IMAGE_NAME: d4v1d007/demo-workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout Repository
      uses: actions/checkout@v4
    -
     name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    -
     name: Set up QEMU
     uses: docker/setup-qemu-action@v3
    -
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3
    -
     name: Build and push
     uses: docker/build-push-action@v6
     with:
      push: true
      tags: d4v1d007/demo-workflow:latest
  deploy-to-vm:
   needs: build-and-push
   runs-on: ubuntu-latest
   steps:
   - name: Deploy over SSH
     uses: appleboy/ssh-action@v1.0.0
     with:
      host: ${{ secrets.VM_HOST }}
      username: ${{ secrets.VM_USER }}
      key: ${{ secrets.VM_SSH_KEY }}
      script: |
       docker pull $REGISTRY/${{ env.DOCKER_IMAGE_NAME }}:latest
       docker stop $CONTAINER_NAME || true
       docker rm $CONTAINER_NAME || true
       docker run -d --name $CONTAINER_NAME -p 80:80 $REGISTRY/${{ env.DOCKER_IMAGE_NAME
       }}:latest
